package com.service;

import java.util.List;

import org.springframework.stereotype.Service;

import com.bean.Manager;

@Service
public interface ManagerService {
	
	public Manager checkLogin(String Mnumber);
	
	 int deleteByPrimaryKey(Integer id);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table manager
	     *
	     * @mbggenerated
	     */
	    int insert(Manager record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table manager
	     *
	     * @mbggenerated
	     */
	    int insertSelective(Manager record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table manager
	     *
	     * @mbggenerated
	     */
	    Manager selectByPrimaryKey(Integer id);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table manager
	     *
	     * @mbggenerated
	     */
	    int updateByPrimaryKeySelective(Manager record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table manager
	     *
	     * @mbggenerated
	     */
	    int updateByPrimaryKey(Manager record);
	    

		Manager selectManagerByMnumber(String mnumber);
		
		
	   List<Manager> selectAllManager(Integer cid);
}
