package com.service;

import com.bean.OldUsers;

public interface OldUsersService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int insert(OldUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int insertSelective(OldUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    OldUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OldUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OldUsers record);
}
