package com.service;

import java.util.List;
import java.util.Map;

import com.bean.Opinions;

public interface OpinionsService {
	List<Opinions> selectByUidOpinions(String uid);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opinions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opinions
     *
     * @mbggenerated
     */
    int insert(Opinions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opinions
     *
     * @mbggenerated
     */
    int insertSelective(Opinions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opinions
     *
     * @mbggenerated
     */
    Opinions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opinions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Opinions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opinions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Opinions record);
    
	List<Opinions> selectByPidOpinions(Map map);
    int selectByPidOpinionsCount(Map map);
    double selectByPidOpinionsAvg(Integer pid);
}
