package com.service;

import java.util.List;

import com.bean.Orderdetails;

public interface OrderdetailsService {
	List<Orderdetails> selectByOrdersId(String oid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int insert(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int insertSelective(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    Orderdetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Orderdetails record);
}
