package com.service;

import java.util.List;
import java.util.Map;

import com.bean.Orders;

public interface OrdersService {
	Double selectOrdersAllMoneysYear();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int insertSelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	Orders selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Orders record);
	public List<Orders> selectOrders();   //查询订单
	
	public List<Orders> selectByorderstatus(int orderstatus);   //查询各种类型 待发 待收 接收
	List<Orders> selectFrontOrderstatus(Map map);
	Integer selectByorderstatusCount(Map map);

}
