package com.service;

import java.util.List;

import org.springframework.stereotype.Service;

import com.bean.Profile;

@Service
public interface ProfileService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated
     */
    int insert(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated
     */
    int insertSelective(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Profile record);
	
	Profile selectByPrimaryKey(Integer id);

	public void insertProfileByUid(Profile profile);

	public List<Profile> selectProfileByUid(String uid);

	public void updateAddressByPrimarykey(Profile profile);

	public void deleteAddressByPrimarykey(Integer id);

}
