package com.service;

import java.util.List;

import com.bean.Showsphotos;

public interface ShowsphotosService {

	 int deleteByPrimaryKey(Integer id);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table showsphotos
	     *
	     * @mbggenerated
	     */
	    int insert(Showsphotos record);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table showsphotos
	     *
	     * @mbggenerated
	     */
	    void insertSelective(Showsphotos record);   //插入图片方法

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table showsphotos
	     *
	     * @mbggenerated
	     */
	    int updateByPrimaryKey(Showsphotos record);
	    Showsphotos selectByPrimaryKey(Integer id);

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method corresponds to the database table showsphotos
	     *
	     * @mbggenerated
	     */
	    int updateByPrimaryKeySelective(Showsphotos record);  //根据id更改showphotos
	    void insertFrompidimage(Showsphotos record);        //根据对象插入
	    
	    List<Showsphotos> selectBypid(int pid);  //根据pid查询Showsphotos
}
