package com.service;

import java.util.List;

import com.bean.Speak;

public interface SpeakService {
	List<Speak> selectByUidFoot(String uidfoot);
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speak
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speak
     *
     * @mbggenerated
     */
    int insert(Speak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speak
     *
     * @mbggenerated
     */
    int insertSelective(Speak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speak
     *
     * @mbggenerated
     */
    Speak selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speak
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Speak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speak
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Speak record);
}
