package com.dao;

import java.util.List;
import java.util.Map;

import com.bean.Activitydetailinfo;

public interface ActivitydetailinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailinfo
     *
     * @mbggenerated
     */
    int insert(Activitydetailinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailinfo
     *
     * @mbggenerated
     */
    int insertSelective(Activitydetailinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailinfo
     *
     * @mbggenerated
     */
    Activitydetailinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Activitydetailinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Activitydetailinfo record);
    
    List<Activitydetailinfo> selectByMid(Integer mid);
    /*---------前台-------*/
	//所有的活动
	public List<Activitydetailinfo> findAllActiveInfo(Map map);
	//活动详情
	public Activitydetailinfo findactiveDetailById(Integer id);
	//最新活动
	public List<Activitydetailinfo> findNewActiveInfo();
	//活动条数
	public int getActivityCount();
    
    
}