package com.dao;

import java.util.List;
import java.util.Map;

import com.bean.Activitydetailoldusers;

public interface ActivitydetailoldusersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailoldusers
     *
     * @mbggenerated
     */
	//查看参加记录
		public List<Activitydetailoldusers> findMyJoninActivies(Map map);
		//删除参加记录
		public void deleteMyJoninActivies(String uid);
		//参与活动的记录条数
		public int getMyJoinActivityCount();
		//是否参加了该活动
		public List<Activitydetailoldusers> queryWhetherJoinActivity(Map map);
 public void deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailoldusers
     *
     * @mbggenerated
     */
   public void insert(Activitydetailoldusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailoldusers
     *
     * @mbggenerated
     */
   public void insertSelective(Activitydetailoldusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailoldusers
     *
     * @mbggenerated
     */
   public  Activitydetailoldusers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailoldusers
     *
     * @mbggenerated
     */
   public  int updateByPrimaryKeySelective(Activitydetailoldusers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitydetailoldusers
     *
     * @mbggenerated
     */
   public  int updateByPrimaryKey(Activitydetailoldusers record);
}