package com.dao;

import java.util.List;

import com.bean.Backinformation;

public interface BackinformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backinformation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backinformation
     *
     * @mbggenerated
     */
    int insert(Backinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backinformation
     *
     * @mbggenerated
     */
    int insertSelective(Backinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backinformation
     *
     * @mbggenerated
     */
    Backinformation selectByPrimaryKey(Integer id);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backinformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Backinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backinformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Backinformation record);
    
    List<Backinformation>selectByAuthor(Integer author);
    
    List<Backinformation>selectAllByAuthor(Integer author);
}