package com.dao;

import java.util.List;
import java.util.Map;

import com.bean.Credit;

public interface CreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbggenerated
     */
    void deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbggenerated
     */
    int insert(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbggenerated
     */
    void insertSelective(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbggenerated
     */
    Credit selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbggenerated
     */
    void updateByPrimaryKeySelective(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbggenerated
     */
    void updateByPrimaryKey(Credit record);
    
    List<Credit> selectCredit();    //查看所有用户的积分
    
    public Credit selectCreditByUid(String uid);  //查看当前登录用户的积分
    public void updateCreditByBuy(Map<String, Object> map);  //用户买产品后积分增加
    public void updateCreditByExchange(Map<String, Object> map);  //用户通过积分兑换商品后积分减少
    
}