package com.dao;

import java.util.List;
import java.util.Map;

import com.bean.Edunews;

public interface EdunewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edunews
     *
     * @mbggenerated
     */
	public void addEdu(Edunews edunews);
	public void deleteEduById(Integer id);
	public void updateEduById(Edunews edunews);
	public Edunews selectEduById(Integer id);
	public List<Edunews>selectAllEdu();
	public List<Edunews>queryEduByConditions(String findEduByConditions);
    public int eduCount();
    public List<Edunews> findAllEduNews(Map map);
	int deleteByPrimaryKey(Integer id);
    public List<Edunews> findHotNews();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edunews
     *
     * @mbggenerated
     */
    int insert(Edunews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edunews
     *
     * @mbggenerated
     */
    int insertSelective(Edunews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edunews
     *
     * @mbggenerated
     */
    Edunews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edunews
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Edunews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edunews
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Edunews record);
}