package com.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.bean.Frontinformation;
@Repository("frontinformationMapper")
public interface FrontinformationMapper {
	List<String> selectAllKinds(Map map);
	int selectByMidCount(Map map);
	Frontinformation selectByKey(Integer id);
	List<Frontinformation> selectByMid(Map map);
	List<Frontinformation> selectAllFrontinformation();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frontinformation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frontinformation
     *
     * @mbggenerated
     */
    int insert(Frontinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frontinformation
     *
     * @mbggenerated
     */
    int insertSelective(Frontinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frontinformation
     *
     * @mbggenerated
     */
    Frontinformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frontinformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Frontinformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frontinformation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Frontinformation record);
    
    //首页用于轮播的方法，返回最新的4条新闻
    List<Frontinformation> selectFour();
    
    //信息页面的所有列表信息，按照时间顺序
    List<Frontinformation> selectAll();
    
    
	List<Frontinformation> selectEight(String newstitle);
}