package com.dao;

import org.springframework.stereotype.Repository;

import com.bean.Groupdetail;
@Repository("groupdetailMapper")
public interface GroupdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupdetail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupdetail
     *
     * @mbggenerated
     */
    int insert(Groupdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupdetail
     *
     * @mbggenerated
     */
    int insertSelective(Groupdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupdetail
     *
     * @mbggenerated
     */
    Groupdetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupdetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Groupdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupdetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Groupdetail record);
    
    Groupdetail selectByUidAndGid(Groupdetail record);
    
}