package com.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.bean.Localarea;

@Repository("localareaMapper")
public interface LocalareaMapper {
	Localarea findTheName(String provincename);
	List<Localarea> findAllLocalAreaMap(Map map);
	int findAllCounts();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
	public int deleteLocalAreaById(Localarea localArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    int insert(Localarea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    public int addLocalArea(Localarea localArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    
    public List<Localarea> findLocalAreaByRecord(Localarea localArea);
    public List<Localarea> findAllLocalArea();
    Localarea selectByPrimaryKey(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    public int updateLocalAreaById(Localarea localArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Localarea record);
    int deleteByPrimaryKey(Integer id);
}