package com.dao;

import java.util.List;

import com.bean.Localarea;

public interface LocalareaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
	public void deleteLocalAreaById(Localarea localArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    int insert(Localarea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    public void addLocalArea(Localarea localArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    
    public List<Localarea> findLocalAreaByRecord(Localarea localArea);
    public List<Localarea> findAllLocalArea();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    public void updateLocalAreaById(Localarea localArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localarea
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Localarea record);
}