package com.dao;

import java.util.List;

import com.bean.Matchpeoplevideo;

public interface MatchpeoplevideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matchpeoplevideo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);
    public List<Matchpeoplevideo> selectUsersByVideoId(Integer id);
    public List<Matchpeoplevideo> selectVideoByUid(String uid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matchpeoplevideo
     *
     * @mbggenerated
     */
    int insert(Matchpeoplevideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matchpeoplevideo
     *
     * @mbggenerated
     */
    int insertSelective(Matchpeoplevideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matchpeoplevideo
     *
     * @mbggenerated
     */
    Matchpeoplevideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matchpeoplevideo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Matchpeoplevideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table matchpeoplevideo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Matchpeoplevideo record);
}