package com.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.bean.Oldcollection;
import com.bean.Products;
@Repository("oldcollectionMapper")
public interface OldcollectionMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oldcollection
	 *
	 * @mbggenerated
	 */
	int insert(Oldcollection record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oldcollection
	 *
	 * @mbggenerated
	 */
	int insertSelective(Oldcollection record);

	int updateByPrimaryKey(Oldcollection record);

	int delete(Oldcollection record);

	Oldcollection select(Oldcollection record);

	Oldcollection selectCeoinfoByName(String name);
	
	List<Products> selectList(String uid);
}