package com.dao;

import com.bean.OldDiseaselibrary;

public interface OldDiseaselibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int insert(OldDiseaselibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int insertSelective(OldDiseaselibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    OldDiseaselibrary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OldDiseaselibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OldDiseaselibrary record);
}