package com.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.bean.OldDiseaselibrary;
@Repository("oldDiseaselibraryMapper")
public interface OldDiseaselibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int insert(OldDiseaselibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int insertSelective(OldDiseaselibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    OldDiseaselibrary selectByPrimaryKey(Integer id);
    List<OldDiseaselibrary> selectAllDiseaselibrary(Map map);
    public int selectDiseaselibraryCount();
    public List<OldDiseaselibrary> findAllDiseaselibrary();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OldDiseaselibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseaselibrary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OldDiseaselibrary record);

	List<OldDiseaselibrary> selectDiseaselibrary(String key);

	OldDiseaselibrary getDiseaseIdByName(String name);
}