package com.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.bean.OldUsers;
@Repository("oldUsersMapper")
public interface OldUsersMapper {
	List<OldUsers> selectByLikeUserName(Map map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int insert(OldUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int insertSelective(OldUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    OldUsers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OldUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_Users
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OldUsers record);
    
    public OldUsers selectByUid(String uid);
    
    public void updateByUidSelective(OldUsers oldUsers);
}