package com.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.bean.Orderdetails;
@Repository("orderdetailsMapper")
public interface OrderdetailsMapper {
	int insertSelectiveList(List list);
	List<Orderdetails> selectByOrdersId(String oid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int insert(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int insertSelective(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    Orderdetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Orderdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderDetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Orderdetails record);
    public 	List<Orderdetails> querySalePrountCount(Integer pid);
}