package com.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.bean.Orders;
@Repository("ordersMapper")
public interface OrdersMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int insertSelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	Orders selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table orders
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Orders record);

	public List<Orders> selectOrders();

	public List<Orders> selectByorderstatus(int orderstatus);

}