package com.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.bean.Returninfo;
@Repository("returninfoMapper")
public interface ReturninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returninfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returninfo
     *
     * @mbggenerated
     */
    int insert(Returninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returninfo
     *
     * @mbggenerated
     */
    int insertSelective(Returninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returninfo
     *
     * @mbggenerated
     */
    Returninfo selectByPrimaryKey(Integer id);
    List<Returninfo> selectByUid(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returninfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Returninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returninfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Returninfo record);
}