package com.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.bean.ShoppingCart;
@Repository("shoppingCartMapper")
public interface ShoppingCartMapper {
	//修改
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated
     */
    void deleteByPrimaryKey(Integer id);    //根据id删除购物车对象
    int insert(ShoppingCart record);
    void insertSelective(ShoppingCart record);     //插入购物车对象

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated
     */
    ShoppingCart selectByPrimaryKey(Integer id);    //根据id查询购物车对象

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShoppingCart record);  //根据id 传入购物车对象  修改购物车表

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingCart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShoppingCart record);    //根据id 传入购物车对象  修改购物车表
    
    void insertjiancartcount(int id);   //根据购物车id 减少购物车对象中商品的数量
    
    void insertAddcartcount(int id);   //根据购物车id 增加购物车对象中商品的数量
    
    void delectProductsByuid(int uid);  //根据用户删除购物车对象
    
    int insertByaproduvts(ShoppingCart record);   //根据用户账号和商品id去购物表里面查询记录 即是看购物表里面是否已经存在这个购物车
    
    void updateAddproducts(ShoppingCart record);  //根据用户账号和商品id增加购物车中该条记录的商品数量
    ShoppingCart selectByaproduvts(ShoppingCart record);
    List<ShoppingCart> selectByaproduvtsList(Map map);
    int deleteByPrimaryKeyList(Map map);
}