package com.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.bean.Watchhistory;
@Repository("watchhistoryMapper")
public interface WatchhistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchhistory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);
    //查询是否观看过
    public List<Watchhistory> whetherSeen(Map map);
    //添加观看记录
    public void addSeenHistory(Watchhistory watchhistory);
    //显示观看记录
    public List<Watchhistory> myWatched(String userUid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchhistory
     *
     * @mbggenerated
     */
    int insert(Watchhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchhistory
     *
     * @mbggenerated
     */
    int insertSelective(Watchhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchhistory
     *
     * @mbggenerated
     */
    Watchhistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchhistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Watchhistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watchhistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Watchhistory record);
}