package com.bean;

import java.util.Date;

public class Backinformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.news
     *
     * @mbggenerated
     */
    private String news;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.author
     *
     * @mbggenerated
     */
    private Integer author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended1
     *
     * @mbggenerated
     */
    private String extended1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended2
     *
     * @mbggenerated
     */
    private String extended2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended3
     *
     * @mbggenerated
     */
    private String extended3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended4
     *
     * @mbggenerated
     */
    private String extended4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended5
     *
     * @mbggenerated
     */
    private String extended5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended6
     *
     * @mbggenerated
     */
    private String extended6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended7
     *
     * @mbggenerated
     */
    private String extended7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended8
     *
     * @mbggenerated
     */
    private String extended8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended9
     *
     * @mbggenerated
     */
    private String extended9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended10
     *
     * @mbggenerated
     */
    private String extended10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended11
     *
     * @mbggenerated
     */
    private String extended11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended12
     *
     * @mbggenerated
     */
    private String extended12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended13
     *
     * @mbggenerated
     */
    private String extended13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended14
     *
     * @mbggenerated
     */
    private String extended14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended15
     *
     * @mbggenerated
     */
    private String extended15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended16
     *
     * @mbggenerated
     */
    private String extended16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended17
     *
     * @mbggenerated
     */
    private String extended17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended18
     *
     * @mbggenerated
     */
    private String extended18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended19
     *
     * @mbggenerated
     */
    private String extended19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backinformation.extended20
     *
     * @mbggenerated
     */
    private String extended20;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backinformation
     *
     * @mbggenerated
     */
    public Backinformation(Integer id, String title, String news, Date time, Integer author, String extended1, String extended2, String extended3, String extended4, String extended5, String extended6, String extended7, String extended8, String extended9, String extended10, String extended11, String extended12, String extended13, String extended14, String extended15, String extended16, String extended17, String extended18, String extended19, String extended20) {
        this.id = id;
        this.title = title;
        this.news = news;
        this.time = time;
        this.author = author;
        this.extended1 = extended1;
        this.extended2 = extended2;
        this.extended3 = extended3;
        this.extended4 = extended4;
        this.extended5 = extended5;
        this.extended6 = extended6;
        this.extended7 = extended7;
        this.extended8 = extended8;
        this.extended9 = extended9;
        this.extended10 = extended10;
        this.extended11 = extended11;
        this.extended12 = extended12;
        this.extended13 = extended13;
        this.extended14 = extended14;
        this.extended15 = extended15;
        this.extended16 = extended16;
        this.extended17 = extended17;
        this.extended18 = extended18;
        this.extended19 = extended19;
        this.extended20 = extended20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backinformation
     *
     * @mbggenerated
     */
    public Backinformation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.id
     *
     * @return the value of backinformation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.id
     *
     * @param id the value for backinformation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.title
     *
     * @return the value of backinformation.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.title
     *
     * @param title the value for backinformation.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.news
     *
     * @return the value of backinformation.news
     *
     * @mbggenerated
     */
    public String getNews() {
        return news;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.news
     *
     * @param news the value for backinformation.news
     *
     * @mbggenerated
     */
    public void setNews(String news) {
        this.news = news == null ? null : news.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.time
     *
     * @return the value of backinformation.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.time
     *
     * @param time the value for backinformation.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.author
     *
     * @return the value of backinformation.author
     *
     * @mbggenerated
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.author
     *
     * @param author the value for backinformation.author
     *
     * @mbggenerated
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended1
     *
     * @return the value of backinformation.extended1
     *
     * @mbggenerated
     */
    public String getExtended1() {
        return extended1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended1
     *
     * @param extended1 the value for backinformation.extended1
     *
     * @mbggenerated
     */
    public void setExtended1(String extended1) {
        this.extended1 = extended1 == null ? null : extended1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended2
     *
     * @return the value of backinformation.extended2
     *
     * @mbggenerated
     */
    public String getExtended2() {
        return extended2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended2
     *
     * @param extended2 the value for backinformation.extended2
     *
     * @mbggenerated
     */
    public void setExtended2(String extended2) {
        this.extended2 = extended2 == null ? null : extended2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended3
     *
     * @return the value of backinformation.extended3
     *
     * @mbggenerated
     */
    public String getExtended3() {
        return extended3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended3
     *
     * @param extended3 the value for backinformation.extended3
     *
     * @mbggenerated
     */
    public void setExtended3(String extended3) {
        this.extended3 = extended3 == null ? null : extended3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended4
     *
     * @return the value of backinformation.extended4
     *
     * @mbggenerated
     */
    public String getExtended4() {
        return extended4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended4
     *
     * @param extended4 the value for backinformation.extended4
     *
     * @mbggenerated
     */
    public void setExtended4(String extended4) {
        this.extended4 = extended4 == null ? null : extended4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended5
     *
     * @return the value of backinformation.extended5
     *
     * @mbggenerated
     */
    public String getExtended5() {
        return extended5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended5
     *
     * @param extended5 the value for backinformation.extended5
     *
     * @mbggenerated
     */
    public void setExtended5(String extended5) {
        this.extended5 = extended5 == null ? null : extended5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended6
     *
     * @return the value of backinformation.extended6
     *
     * @mbggenerated
     */
    public String getExtended6() {
        return extended6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended6
     *
     * @param extended6 the value for backinformation.extended6
     *
     * @mbggenerated
     */
    public void setExtended6(String extended6) {
        this.extended6 = extended6 == null ? null : extended6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended7
     *
     * @return the value of backinformation.extended7
     *
     * @mbggenerated
     */
    public String getExtended7() {
        return extended7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended7
     *
     * @param extended7 the value for backinformation.extended7
     *
     * @mbggenerated
     */
    public void setExtended7(String extended7) {
        this.extended7 = extended7 == null ? null : extended7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended8
     *
     * @return the value of backinformation.extended8
     *
     * @mbggenerated
     */
    public String getExtended8() {
        return extended8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended8
     *
     * @param extended8 the value for backinformation.extended8
     *
     * @mbggenerated
     */
    public void setExtended8(String extended8) {
        this.extended8 = extended8 == null ? null : extended8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended9
     *
     * @return the value of backinformation.extended9
     *
     * @mbggenerated
     */
    public String getExtended9() {
        return extended9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended9
     *
     * @param extended9 the value for backinformation.extended9
     *
     * @mbggenerated
     */
    public void setExtended9(String extended9) {
        this.extended9 = extended9 == null ? null : extended9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended10
     *
     * @return the value of backinformation.extended10
     *
     * @mbggenerated
     */
    public String getExtended10() {
        return extended10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended10
     *
     * @param extended10 the value for backinformation.extended10
     *
     * @mbggenerated
     */
    public void setExtended10(String extended10) {
        this.extended10 = extended10 == null ? null : extended10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended11
     *
     * @return the value of backinformation.extended11
     *
     * @mbggenerated
     */
    public String getExtended11() {
        return extended11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended11
     *
     * @param extended11 the value for backinformation.extended11
     *
     * @mbggenerated
     */
    public void setExtended11(String extended11) {
        this.extended11 = extended11 == null ? null : extended11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended12
     *
     * @return the value of backinformation.extended12
     *
     * @mbggenerated
     */
    public String getExtended12() {
        return extended12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended12
     *
     * @param extended12 the value for backinformation.extended12
     *
     * @mbggenerated
     */
    public void setExtended12(String extended12) {
        this.extended12 = extended12 == null ? null : extended12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended13
     *
     * @return the value of backinformation.extended13
     *
     * @mbggenerated
     */
    public String getExtended13() {
        return extended13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended13
     *
     * @param extended13 the value for backinformation.extended13
     *
     * @mbggenerated
     */
    public void setExtended13(String extended13) {
        this.extended13 = extended13 == null ? null : extended13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended14
     *
     * @return the value of backinformation.extended14
     *
     * @mbggenerated
     */
    public String getExtended14() {
        return extended14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended14
     *
     * @param extended14 the value for backinformation.extended14
     *
     * @mbggenerated
     */
    public void setExtended14(String extended14) {
        this.extended14 = extended14 == null ? null : extended14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended15
     *
     * @return the value of backinformation.extended15
     *
     * @mbggenerated
     */
    public String getExtended15() {
        return extended15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended15
     *
     * @param extended15 the value for backinformation.extended15
     *
     * @mbggenerated
     */
    public void setExtended15(String extended15) {
        this.extended15 = extended15 == null ? null : extended15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended16
     *
     * @return the value of backinformation.extended16
     *
     * @mbggenerated
     */
    public String getExtended16() {
        return extended16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended16
     *
     * @param extended16 the value for backinformation.extended16
     *
     * @mbggenerated
     */
    public void setExtended16(String extended16) {
        this.extended16 = extended16 == null ? null : extended16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended17
     *
     * @return the value of backinformation.extended17
     *
     * @mbggenerated
     */
    public String getExtended17() {
        return extended17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended17
     *
     * @param extended17 the value for backinformation.extended17
     *
     * @mbggenerated
     */
    public void setExtended17(String extended17) {
        this.extended17 = extended17 == null ? null : extended17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended18
     *
     * @return the value of backinformation.extended18
     *
     * @mbggenerated
     */
    public String getExtended18() {
        return extended18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended18
     *
     * @param extended18 the value for backinformation.extended18
     *
     * @mbggenerated
     */
    public void setExtended18(String extended18) {
        this.extended18 = extended18 == null ? null : extended18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended19
     *
     * @return the value of backinformation.extended19
     *
     * @mbggenerated
     */
    public String getExtended19() {
        return extended19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended19
     *
     * @param extended19 the value for backinformation.extended19
     *
     * @mbggenerated
     */
    public void setExtended19(String extended19) {
        this.extended19 = extended19 == null ? null : extended19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backinformation.extended20
     *
     * @return the value of backinformation.extended20
     *
     * @mbggenerated
     */
    public String getExtended20() {
        return extended20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backinformation.extended20
     *
     * @param extended20 the value for backinformation.extended20
     *
     * @mbggenerated
     */
    public void setExtended20(String extended20) {
        this.extended20 = extended20 == null ? null : extended20.trim();
    }
}