package com.bean;

import java.util.Date;
import java.util.List;

public class OldDiseasedetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.id
     *
     * @mbggenerated
     */
    private Integer id;
    private List<OldSickness> listOldSickness;

   

	public List<OldSickness> getListOldSickness() {
		return listOldSickness;
	}

	public void setListOldSickness(List<OldSickness> listOldSickness) {
		this.listOldSickness = listOldSickness;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.treat_tiem
     *
     * @mbggenerated
     */
    private Date treatTiem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.history
     *
     * @mbggenerated
     */
    private String history;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.suggest
     *
     * @mbggenerated
     */
    private String suggest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended1
     *
     * @mbggenerated
     */
    private String extended1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended2
     *
     * @mbggenerated
     */
    private String extended2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended3
     *
     * @mbggenerated
     */
    private String extended3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended4
     *
     * @mbggenerated
     */
    private String extended4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended5
     *
     * @mbggenerated
     */
    private String extended5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended6
     *
     * @mbggenerated
     */
    private String extended6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended7
     *
     * @mbggenerated
     */
    private String extended7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended8
     *
     * @mbggenerated
     */
    private String extended8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended9
     *
     * @mbggenerated
     */
    private String extended9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended10
     *
     * @mbggenerated
     */
    private String extended10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended11
     *
     * @mbggenerated
     */
    private String extended11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended12
     *
     * @mbggenerated
     */
    private String extended12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended13
     *
     * @mbggenerated
     */
    private String extended13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended14
     *
     * @mbggenerated
     */
    private String extended14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended15
     *
     * @mbggenerated
     */
    private String extended15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended16
     *
     * @mbggenerated
     */
    private String extended16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended17
     *
     * @mbggenerated
     */
    private String extended17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended18
     *
     * @mbggenerated
     */
    private String extended18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended19
     *
     * @mbggenerated
     */
    private String extended19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column old_diseasedetails.extended20
     *
     * @mbggenerated
     */
    private String extended20;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseasedetails
     *
     * @mbggenerated
     */
    public OldDiseasedetails(Integer id, Date treatTiem, String history, String suggest, String uid, String extended1, String extended2, String extended3, String extended4, String extended5, String extended6, String extended7, String extended8, String extended9, String extended10, String extended11, String extended12, String extended13, String extended14, String extended15, String extended16, String extended17, String extended18, String extended19, String extended20) {
        this.id = id;
        this.treatTiem = treatTiem;
        this.history = history;
        this.suggest = suggest;
        this.uid = uid;
        this.extended1 = extended1;
        this.extended2 = extended2;
        this.extended3 = extended3;
        this.extended4 = extended4;
        this.extended5 = extended5;
        this.extended6 = extended6;
        this.extended7 = extended7;
        this.extended8 = extended8;
        this.extended9 = extended9;
        this.extended10 = extended10;
        this.extended11 = extended11;
        this.extended12 = extended12;
        this.extended13 = extended13;
        this.extended14 = extended14;
        this.extended15 = extended15;
        this.extended16 = extended16;
        this.extended17 = extended17;
        this.extended18 = extended18;
        this.extended19 = extended19;
        this.extended20 = extended20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table old_diseasedetails
     *
     * @mbggenerated
     */
    public OldDiseasedetails() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.id
     *
     * @return the value of old_diseasedetails.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.id
     *
     * @param id the value for old_diseasedetails.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.treat_tiem
     *
     * @return the value of old_diseasedetails.treat_tiem
     *
     * @mbggenerated
     */
    public Date getTreatTiem() {
        return treatTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.treat_tiem
     *
     * @param treatTiem the value for old_diseasedetails.treat_tiem
     *
     * @mbggenerated
     */
    public void setTreatTiem(Date treatTiem) {
        this.treatTiem = treatTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.history
     *
     * @return the value of old_diseasedetails.history
     *
     * @mbggenerated
     */
    public String getHistory() {
        return history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.history
     *
     * @param history the value for old_diseasedetails.history
     *
     * @mbggenerated
     */
    public void setHistory(String history) {
        this.history = history == null ? null : history.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.suggest
     *
     * @return the value of old_diseasedetails.suggest
     *
     * @mbggenerated
     */
    public String getSuggest() {
        return suggest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.suggest
     *
     * @param suggest the value for old_diseasedetails.suggest
     *
     * @mbggenerated
     */
    public void setSuggest(String suggest) {
        this.suggest = suggest == null ? null : suggest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.uid
     *
     * @return the value of old_diseasedetails.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.uid
     *
     * @param uid the value for old_diseasedetails.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended1
     *
     * @return the value of old_diseasedetails.extended1
     *
     * @mbggenerated
     */
    public String getExtended1() {
        return extended1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended1
     *
     * @param extended1 the value for old_diseasedetails.extended1
     *
     * @mbggenerated
     */
    public void setExtended1(String extended1) {
        this.extended1 = extended1 == null ? null : extended1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended2
     *
     * @return the value of old_diseasedetails.extended2
     *
     * @mbggenerated
     */
    public String getExtended2() {
        return extended2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended2
     *
     * @param extended2 the value for old_diseasedetails.extended2
     *
     * @mbggenerated
     */
    public void setExtended2(String extended2) {
        this.extended2 = extended2 == null ? null : extended2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended3
     *
     * @return the value of old_diseasedetails.extended3
     *
     * @mbggenerated
     */
    public String getExtended3() {
        return extended3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended3
     *
     * @param extended3 the value for old_diseasedetails.extended3
     *
     * @mbggenerated
     */
    public void setExtended3(String extended3) {
        this.extended3 = extended3 == null ? null : extended3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended4
     *
     * @return the value of old_diseasedetails.extended4
     *
     * @mbggenerated
     */
    public String getExtended4() {
        return extended4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended4
     *
     * @param extended4 the value for old_diseasedetails.extended4
     *
     * @mbggenerated
     */
    public void setExtended4(String extended4) {
        this.extended4 = extended4 == null ? null : extended4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended5
     *
     * @return the value of old_diseasedetails.extended5
     *
     * @mbggenerated
     */
    public String getExtended5() {
        return extended5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended5
     *
     * @param extended5 the value for old_diseasedetails.extended5
     *
     * @mbggenerated
     */
    public void setExtended5(String extended5) {
        this.extended5 = extended5 == null ? null : extended5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended6
     *
     * @return the value of old_diseasedetails.extended6
     *
     * @mbggenerated
     */
    public String getExtended6() {
        return extended6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended6
     *
     * @param extended6 the value for old_diseasedetails.extended6
     *
     * @mbggenerated
     */
    public void setExtended6(String extended6) {
        this.extended6 = extended6 == null ? null : extended6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended7
     *
     * @return the value of old_diseasedetails.extended7
     *
     * @mbggenerated
     */
    public String getExtended7() {
        return extended7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended7
     *
     * @param extended7 the value for old_diseasedetails.extended7
     *
     * @mbggenerated
     */
    public void setExtended7(String extended7) {
        this.extended7 = extended7 == null ? null : extended7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended8
     *
     * @return the value of old_diseasedetails.extended8
     *
     * @mbggenerated
     */
    public String getExtended8() {
        return extended8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended8
     *
     * @param extended8 the value for old_diseasedetails.extended8
     *
     * @mbggenerated
     */
    public void setExtended8(String extended8) {
        this.extended8 = extended8 == null ? null : extended8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended9
     *
     * @return the value of old_diseasedetails.extended9
     *
     * @mbggenerated
     */
    public String getExtended9() {
        return extended9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended9
     *
     * @param extended9 the value for old_diseasedetails.extended9
     *
     * @mbggenerated
     */
    public void setExtended9(String extended9) {
        this.extended9 = extended9 == null ? null : extended9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended10
     *
     * @return the value of old_diseasedetails.extended10
     *
     * @mbggenerated
     */
    public String getExtended10() {
        return extended10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended10
     *
     * @param extended10 the value for old_diseasedetails.extended10
     *
     * @mbggenerated
     */
    public void setExtended10(String extended10) {
        this.extended10 = extended10 == null ? null : extended10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended11
     *
     * @return the value of old_diseasedetails.extended11
     *
     * @mbggenerated
     */
    public String getExtended11() {
        return extended11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended11
     *
     * @param extended11 the value for old_diseasedetails.extended11
     *
     * @mbggenerated
     */
    public void setExtended11(String extended11) {
        this.extended11 = extended11 == null ? null : extended11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended12
     *
     * @return the value of old_diseasedetails.extended12
     *
     * @mbggenerated
     */
    public String getExtended12() {
        return extended12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended12
     *
     * @param extended12 the value for old_diseasedetails.extended12
     *
     * @mbggenerated
     */
    public void setExtended12(String extended12) {
        this.extended12 = extended12 == null ? null : extended12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended13
     *
     * @return the value of old_diseasedetails.extended13
     *
     * @mbggenerated
     */
    public String getExtended13() {
        return extended13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended13
     *
     * @param extended13 the value for old_diseasedetails.extended13
     *
     * @mbggenerated
     */
    public void setExtended13(String extended13) {
        this.extended13 = extended13 == null ? null : extended13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended14
     *
     * @return the value of old_diseasedetails.extended14
     *
     * @mbggenerated
     */
    public String getExtended14() {
        return extended14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended14
     *
     * @param extended14 the value for old_diseasedetails.extended14
     *
     * @mbggenerated
     */
    public void setExtended14(String extended14) {
        this.extended14 = extended14 == null ? null : extended14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended15
     *
     * @return the value of old_diseasedetails.extended15
     *
     * @mbggenerated
     */
    public String getExtended15() {
        return extended15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended15
     *
     * @param extended15 the value for old_diseasedetails.extended15
     *
     * @mbggenerated
     */
    public void setExtended15(String extended15) {
        this.extended15 = extended15 == null ? null : extended15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended16
     *
     * @return the value of old_diseasedetails.extended16
     *
     * @mbggenerated
     */
    public String getExtended16() {
        return extended16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended16
     *
     * @param extended16 the value for old_diseasedetails.extended16
     *
     * @mbggenerated
     */
    public void setExtended16(String extended16) {
        this.extended16 = extended16 == null ? null : extended16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended17
     *
     * @return the value of old_diseasedetails.extended17
     *
     * @mbggenerated
     */
    public String getExtended17() {
        return extended17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended17
     *
     * @param extended17 the value for old_diseasedetails.extended17
     *
     * @mbggenerated
     */
    public void setExtended17(String extended17) {
        this.extended17 = extended17 == null ? null : extended17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended18
     *
     * @return the value of old_diseasedetails.extended18
     *
     * @mbggenerated
     */
    public String getExtended18() {
        return extended18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended18
     *
     * @param extended18 the value for old_diseasedetails.extended18
     *
     * @mbggenerated
     */
    public void setExtended18(String extended18) {
        this.extended18 = extended18 == null ? null : extended18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended19
     *
     * @return the value of old_diseasedetails.extended19
     *
     * @mbggenerated
     */
    public String getExtended19() {
        return extended19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended19
     *
     * @param extended19 the value for old_diseasedetails.extended19
     *
     * @mbggenerated
     */
    public void setExtended19(String extended19) {
        this.extended19 = extended19 == null ? null : extended19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column old_diseasedetails.extended20
     *
     * @return the value of old_diseasedetails.extended20
     *
     * @mbggenerated
     */
    public String getExtended20() {
        return extended20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column old_diseasedetails.extended20
     *
     * @param extended20 the value for old_diseasedetails.extended20
     *
     * @mbggenerated
     */
    public void setExtended20(String extended20) {
        this.extended20 = extended20 == null ? null : extended20.trim();
    }

}