package com.bean;

import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Products {
	
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	private Date datesDay;

	public Date getDatesDay() {
		return datesDay;
	}

	public void setDatesDay(Date datesDay) {
		this.datesDay = datesDay;
	}

	@JsonFormat(pattern = "yyyy-MM", timezone = "GMT+8")
	private Date dates;

	public Date getDates() {
		return dates;
	}

	public void setDates(Date dates) {
		this.dates = dates;
	}

	// 钱
	private Double sumMoney;
	// 数量
	private Integer sumNum;
	private Classification classification;

	public Classification getClassification() {
		return classification;
	}

	public void setClassification(Classification classification) {
		this.classification = classification;
	}

	public Double getSumMoney() {
		return sumMoney;
	}

	public void setSumMoney(Double sumMoney) {
		this.sumMoney = sumMoney;
	}

	public Integer getSumNum() {
		return sumNum;
	}

	public void setSumNum(Integer sumNum) {
		this.sumNum = sumNum;
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.id
	 *
	 * @mbggenerated
	 */
	private Integer id; 
	 

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.pname
	 *
	 * @mbggenerated
	 */
	private String pname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.size
	 *
	 * @mbggenerated
	 */
	private String size;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.productscolor
	 *
	 * @mbggenerated
	 */
	private String productscolor;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.productstype1
	 *
	 * @mbggenerated
	 */
	private String productstype1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.productstype2
	 *
	 * @mbggenerated
	 */
	private String productstype2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.price
	 *
	 * @mbggenerated
	 */
	private Double price;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.pdescription
	 *
	 * @mbggenerated
	 */
	private String pdescription;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.count
	 *
	 * @mbggenerated
	 */
	private Integer count;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.tid
	 *
	 * @mbggenerated
	 */
	private Integer tid;
	private List<Showsphotos> listPhotos;

	public List<Showsphotos> getListPhotos() {
		return listPhotos;
	}

	public void setListPhotos(List<Showsphotos> listPhotos) {
		this.listPhotos = listPhotos;
	}

	private Classification classifications;

	public Classification getClassifications() {
		return classifications;
	}

	public void setClassifications(Classification classifications) {
		this.classifications = classifications;
	}

	private Creditshop creditshop;

	public Creditshop getCreditshop() {
		return creditshop;
	}

	public void setCreditshop(Creditshop creditshop) {
		this.creditshop = creditshop;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended1
	 *
	 * @mbggenerated
	 */
	//销量
		private Integer saleProductCount;
		
	    public Integer getSaleProductCount() {
			return saleProductCount;
		}

		public void setSaleProductCount(Integer saleProductCount) {
			this.saleProductCount = saleProductCount;
		}

	//
		private List<OldSickness> oldSickness;
		
		public List<OldSickness> getOldSickness() {
			return oldSickness;
		}

		public void setOldSickness(List<OldSickness> oldSickness) {
			this.oldSickness = oldSickness;
		}

	private String extended1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended2
	 *
	 * @mbggenerated
	 */
	private String extended2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended3
	 *
	 * @mbggenerated
	 */
	private String extended3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended4
	 *
	 * @mbggenerated
	 */
	private String extended4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended5
	 *
	 * @mbggenerated
	 */
	private String extended5;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended6
	 *
	 * @mbggenerated
	 */
	private String extended6;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended7
	 *
	 * @mbggenerated
	 */
	private String extended7;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended8
	 *
	 * @mbggenerated
	 */
	private String extended8;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended9
	 *
	 * @mbggenerated
	 */
	private String extended9;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended10
	 *
	 * @mbggenerated
	 */
	private String extended10;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended11
	 *
	 * @mbggenerated
	 */
	private String extended11;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended12
	 *
	 * @mbggenerated
	 */
	private String extended12;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended13
	 *
	 * @mbggenerated
	 */
	private String extended13;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended14
	 *
	 * @mbggenerated
	 */
	private String extended14;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended15
	 *
	 * @mbggenerated
	 */
	private String extended15;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended16
	 *
	 * @mbggenerated
	 */
	private String extended16;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended17
	 *
	 * @mbggenerated
	 */
	private String extended17;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended18
	 *
	 * @mbggenerated
	 */
	private String extended18;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended19
	 *
	 * @mbggenerated
	 */
	private String extended19;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.extended20
	 *
	 * @mbggenerated
	 */
	private String extended20;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column products.producturl
	 *
	 * @mbggenerated
	 */
	private String producturl;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table products
	 *
	 * @mbggenerated
	 */
	public Products(Integer id, String pname, String size, String productscolor, String productstype1,
			String productstype2, Double price, String pdescription, Integer count, Integer tid, String extended1,
			String extended2, String extended3, String extended4, String extended5, String extended6, String extended7,
			String extended8, String extended9, String extended10, String extended11, String extended12,
			String extended13, String extended14, String extended15, String extended16, String extended17,
			String extended18, String extended19, String extended20, String producturl) {
		this.id = id;
		this.pname = pname;
		this.size = size;
		this.productscolor = productscolor;
		this.productstype1 = productstype1;
		this.productstype2 = productstype2;
		this.price = price;
		this.pdescription = pdescription;
		this.count = count;
		this.tid = tid;
		this.extended1 = extended1;
		this.extended2 = extended2;
		this.extended3 = extended3;
		this.extended4 = extended4;
		this.extended5 = extended5;
		this.extended6 = extended6;
		this.extended7 = extended7;
		this.extended8 = extended8;
		this.extended9 = extended9;
		this.extended10 = extended10;
		this.extended11 = extended11;
		this.extended12 = extended12;
		this.extended13 = extended13;
		this.extended14 = extended14;
		this.extended15 = extended15;
		this.extended16 = extended16;
		this.extended17 = extended17;
		this.extended18 = extended18;
		this.extended19 = extended19;
		this.extended20 = extended20;
		this.producturl = producturl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table products
	 *
	 * @mbggenerated
	 */
	public Products() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.id
	 *
	 * @return the value of products.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.id
	 *
	 * @param id
	 *            the value for products.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.pname
	 *
	 * @return the value of products.pname
	 *
	 * @mbggenerated
	 */
	public String getPname() {
		return pname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.pname
	 *
	 * @param pname
	 *            the value for products.pname
	 *
	 * @mbggenerated
	 */
	public void setPname(String pname) {
		this.pname = pname == null ? null : pname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.size
	 *
	 * @return the value of products.size
	 *
	 * @mbggenerated
	 */
	public String getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.size
	 *
	 * @param size
	 *            the value for products.size
	 *
	 * @mbggenerated
	 */
	public void setSize(String size) {
		this.size = size == null ? null : size.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.productscolor
	 *
	 * @return the value of products.productscolor
	 *
	 * @mbggenerated
	 */
	public String getProductscolor() {
		return productscolor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.productscolor
	 *
	 * @param productscolor
	 *            the value for products.productscolor
	 *
	 * @mbggenerated
	 */
	public void setProductscolor(String productscolor) {
		this.productscolor = productscolor == null ? null : productscolor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.productstype1
	 *
	 * @return the value of products.productstype1
	 *
	 * @mbggenerated
	 */
	public String getProductstype1() {
		return productstype1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.productstype1
	 *
	 * @param productstype1
	 *            the value for products.productstype1
	 *
	 * @mbggenerated
	 */
	public void setProductstype1(String productstype1) {
		this.productstype1 = productstype1 == null ? null : productstype1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.productstype2
	 *
	 * @return the value of products.productstype2
	 *
	 * @mbggenerated
	 */
	public String getProductstype2() {
		return productstype2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.productstype2
	 *
	 * @param productstype2
	 *            the value for products.productstype2
	 *
	 * @mbggenerated
	 */
	public void setProductstype2(String productstype2) {
		this.productstype2 = productstype2 == null ? null : productstype2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.price
	 *
	 * @return the value of products.price
	 *
	 * @mbggenerated
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.price
	 *
	 * @param price
	 *            the value for products.price
	 *
	 * @mbggenerated
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.pdescription
	 *
	 * @return the value of products.pdescription
	 *
	 * @mbggenerated
	 */
	public String getPdescription() {
		return pdescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.pdescription
	 *
	 * @param pdescription
	 *            the value for products.pdescription
	 *
	 * @mbggenerated
	 */
	public void setPdescription(String pdescription) {
		this.pdescription = pdescription == null ? null : pdescription.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.count
	 *
	 * @return the value of products.count
	 *
	 * @mbggenerated
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.count
	 *
	 * @param count
	 *            the value for products.count
	 *
	 * @mbggenerated
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.tid
	 *
	 * @return the value of products.tid
	 *
	 * @mbggenerated
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.tid
	 *
	 * @param tid
	 *            the value for products.tid
	 *
	 * @mbggenerated
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended1
	 *
	 * @return the value of products.extended1
	 *
	 * @mbggenerated
	 */
	public String getExtended1() {
		return extended1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended1
	 *
	 * @param extended1
	 *            the value for products.extended1
	 *
	 * @mbggenerated
	 */
	public void setExtended1(String extended1) {
		this.extended1 = extended1 == null ? null : extended1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended2
	 *
	 * @return the value of products.extended2
	 *
	 * @mbggenerated
	 */
	public String getExtended2() {
		return extended2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended2
	 *
	 * @param extended2
	 *            the value for products.extended2
	 *
	 * @mbggenerated
	 */
	public void setExtended2(String extended2) {
		this.extended2 = extended2 == null ? null : extended2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended3
	 *
	 * @return the value of products.extended3
	 *
	 * @mbggenerated
	 */
	public String getExtended3() {
		return extended3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended3
	 *
	 * @param extended3
	 *            the value for products.extended3
	 *
	 * @mbggenerated
	 */
	public void setExtended3(String extended3) {
		this.extended3 = extended3 == null ? null : extended3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended4
	 *
	 * @return the value of products.extended4
	 *
	 * @mbggenerated
	 */
	public String getExtended4() {
		return extended4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended4
	 *
	 * @param extended4
	 *            the value for products.extended4
	 *
	 * @mbggenerated
	 */
	public void setExtended4(String extended4) {
		this.extended4 = extended4 == null ? null : extended4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended5
	 *
	 * @return the value of products.extended5
	 *
	 * @mbggenerated
	 */
	public String getExtended5() {
		return extended5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended5
	 *
	 * @param extended5
	 *            the value for products.extended5
	 *
	 * @mbggenerated
	 */
	public void setExtended5(String extended5) {
		this.extended5 = extended5 == null ? null : extended5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended6
	 *
	 * @return the value of products.extended6
	 *
	 * @mbggenerated
	 */
	public String getExtended6() {
		return extended6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended6
	 *
	 * @param extended6
	 *            the value for products.extended6
	 *
	 * @mbggenerated
	 */
	public void setExtended6(String extended6) {
		this.extended6 = extended6 == null ? null : extended6.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended7
	 *
	 * @return the value of products.extended7
	 *
	 * @mbggenerated
	 */
	public String getExtended7() {
		return extended7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended7
	 *
	 * @param extended7
	 *            the value for products.extended7
	 *
	 * @mbggenerated
	 */
	public void setExtended7(String extended7) {
		this.extended7 = extended7 == null ? null : extended7.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended8
	 *
	 * @return the value of products.extended8
	 *
	 * @mbggenerated
	 */
	public String getExtended8() {
		return extended8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended8
	 *
	 * @param extended8
	 *            the value for products.extended8
	 *
	 * @mbggenerated
	 */
	public void setExtended8(String extended8) {
		this.extended8 = extended8 == null ? null : extended8.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended9
	 *
	 * @return the value of products.extended9
	 *
	 * @mbggenerated
	 */
	public String getExtended9() {
		return extended9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended9
	 *
	 * @param extended9
	 *            the value for products.extended9
	 *
	 * @mbggenerated
	 */
	public void setExtended9(String extended9) {
		this.extended9 = extended9 == null ? null : extended9.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended10
	 *
	 * @return the value of products.extended10
	 *
	 * @mbggenerated
	 */
	public String getExtended10() {
		return extended10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended10
	 *
	 * @param extended10
	 *            the value for products.extended10
	 *
	 * @mbggenerated
	 */
	public void setExtended10(String extended10) {
		this.extended10 = extended10 == null ? null : extended10.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended11
	 *
	 * @return the value of products.extended11
	 *
	 * @mbggenerated
	 */
	public String getExtended11() {
		return extended11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended11
	 *
	 * @param extended11
	 *            the value for products.extended11
	 *
	 * @mbggenerated
	 */
	public void setExtended11(String extended11) {
		this.extended11 = extended11 == null ? null : extended11.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended12
	 *
	 * @return the value of products.extended12
	 *
	 * @mbggenerated
	 */
	public String getExtended12() {
		return extended12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended12
	 *
	 * @param extended12
	 *            the value for products.extended12
	 *
	 * @mbggenerated
	 */
	public void setExtended12(String extended12) {
		this.extended12 = extended12 == null ? null : extended12.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended13
	 *
	 * @return the value of products.extended13
	 *
	 * @mbggenerated
	 */
	public String getExtended13() {
		return extended13;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended13
	 *
	 * @param extended13
	 *            the value for products.extended13
	 *
	 * @mbggenerated
	 */
	public void setExtended13(String extended13) {
		this.extended13 = extended13 == null ? null : extended13.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended14
	 *
	 * @return the value of products.extended14
	 *
	 * @mbggenerated
	 */
	public String getExtended14() {
		return extended14;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended14
	 *
	 * @param extended14
	 *            the value for products.extended14
	 *
	 * @mbggenerated
	 */
	public void setExtended14(String extended14) {
		this.extended14 = extended14 == null ? null : extended14.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended15
	 *
	 * @return the value of products.extended15
	 *
	 * @mbggenerated
	 */
	public String getExtended15() {
		return extended15;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended15
	 *
	 * @param extended15
	 *            the value for products.extended15
	 *
	 * @mbggenerated
	 */
	public void setExtended15(String extended15) {
		this.extended15 = extended15 == null ? null : extended15.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended16
	 *
	 * @return the value of products.extended16
	 *
	 * @mbggenerated
	 */
	public String getExtended16() {
		return extended16;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended16
	 *
	 * @param extended16
	 *            the value for products.extended16
	 *
	 * @mbggenerated
	 */
	public void setExtended16(String extended16) {
		this.extended16 = extended16 == null ? null : extended16.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended17
	 *
	 * @return the value of products.extended17
	 *
	 * @mbggenerated
	 */
	public String getExtended17() {
		return extended17;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended17
	 *
	 * @param extended17
	 *            the value for products.extended17
	 *
	 * @mbggenerated
	 */
	public void setExtended17(String extended17) {
		this.extended17 = extended17 == null ? null : extended17.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended18
	 *
	 * @return the value of products.extended18
	 *
	 * @mbggenerated
	 */
	public String getExtended18() {
		return extended18;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended18
	 *
	 * @param extended18
	 *            the value for products.extended18
	 *
	 * @mbggenerated
	 */
	public void setExtended18(String extended18) {
		this.extended18 = extended18 == null ? null : extended18.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended19
	 *
	 * @return the value of products.extended19
	 *
	 * @mbggenerated
	 */
	public String getExtended19() {
		return extended19;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended19
	 *
	 * @param extended19
	 *            the value for products.extended19
	 *
	 * @mbggenerated
	 */
	public void setExtended19(String extended19) {
		this.extended19 = extended19 == null ? null : extended19.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.extended20
	 *
	 * @return the value of products.extended20
	 *
	 * @mbggenerated
	 */
	public String getExtended20() {
		return extended20;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.extended20
	 *
	 * @param extended20
	 *            the value for products.extended20
	 *
	 * @mbggenerated
	 */
	public void setExtended20(String extended20) {
		this.extended20 = extended20 == null ? null : extended20.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column products.producturl
	 *
	 * @return the value of products.producturl
	 *
	 * @mbggenerated
	 */
	public String getProducturl() {
		return producturl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column products.producturl
	 *
	 * @param producturl
	 *            the value for products.producturl
	 *
	 * @mbggenerated
	 */
	public void setProducturl(String producturl) {
		this.producturl = producturl == null ? null : producturl.trim();
	}
}